# Generated by Django 5.0.2 on 2024-05-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_simplify', '0001_initial'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlikepaper',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='userlikepaper',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='userlikepaper',
            constraint=models.UniqueConstraint(fields=('user', 'paper'), name='unique_user_paper'),
        ),
    ]
