# Generated by Django 5.0.2 on 2024-05-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbrowsepaperhistory',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
