# Generated by Django 5.0.2 on 2024-05-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_simplify', '0001_initial'),
        ('user_authentication', '0002_rename_paper_id_userlikepaper_paper_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userlikepaper',
            name='unique_user_paper',
        ),
        migrations.RenameField(
            model_name='userbrowsepaperhistory',
            old_name='paper_id',
            new_name='paper',
        ),
        migrations.RenameField(
            model_name='userbrowsepaperhistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='userbrowsepaperhistory',
            constraint=models.UniqueConstraint(fields=('user', 'paper'), name='user_browser_paper_history'),
        ),
        migrations.AddConstraint(
            model_name='userlikepaper',
            constraint=models.UniqueConstraint(fields=('user', 'paper'), name='user_like_paper'),
        ),
    ]
