# Generated by Django 5.0.2 on 2024-05-18 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('paper_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=400)),
                ('title_ja', models.CharField(max_length=400)),
                ('authors', models.JSONField()),
                ('categories', models.JSONField()),
                ('published', models.DateTimeField()),
                ('content_en', models.TextField()),
                ('pdf_url', models.URLField()),
                ('clicked_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SimplifyAbstract',
            fields=[
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gpt_simplify.paper')),
                ('content_ja', models.TextField()),
                ('content_plain', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='gpt_simplify.simplifyabstract')),
                ('keywords_list', models.JSONField(default=[])),
            ],
        ),
    ]
