# Generated by Django 5.0.2 on 2024-05-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickedPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.CharField(max_length=100, unique=True)),
                ('title_en', models.CharField(max_length=400)),
                ('title_ja', models.CharField(max_length=400)),
                ('author', models.JSONField()),
                ('categories', models.JSONField()),
                ('published', models.DateTimeField()),
                ('content_en', models.TextField()),
                ('pdf_url', models.URLField()),
                ('content_ja', models.TextField()),
                ('content_plain', models.TextField()),
                ('keywords_list', models.JSONField(default=[])),
                ('clicked_count', models.IntegerField(default=1)),
            ],
        ),
    ]
