# Generated by Django 5.0.2 on 2024-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_simplify', '0002_alter_clickedpaper_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickedpaper',
            name='keywords',
        ),
        migrations.AddField(
            model_name='clickedpaper',
            name='keywords_list',
            field=models.JSONField(default=[]),
        ),
    ]
