# Generated by Django 5.0.2 on 2024-02-25 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gpt_simplify', '0003_remove_clickedpaper_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickedpaper',
            name='keywords_list',
            field=models.TextField(),
        ),
    ]
